### ISSUE TITLE
Cannot print out methd code because method because InstructionPointer is set to max

### ISSUE THREAD

**Issue by XenocodeRCE** [xoofx/JitBuddy#1]
Hello :-)
 https://github.com/xoofx/JitBuddy/blob/d9336f5f89e9732558bf92ab8a350f26198eec6e/src/JitBuddy/JitBuddy.cs#L85

This condition is never stepped into because **InstructionPointer** is *always* equal to **endRip**

For references, I am using your ManagedJIT project in order to grab some method's code.

![ ](https://i.imgur.com/v5JlNUN.png)

**Comment by xoofx** [comment]
oops, sorry, forgot to watch the repo and didn't get notified

**Comment by xoofx** [comment]
I believe it should be fixed by `0.2.0`, you can reopen if not.
